_wandb:
    value:
        cli_version: 0.22.2
        e:
            lqimk6v2zb22ks1x93jcbfxwvu1m1ome:
                codePath: wandb_test.py
                codePathLocal: wandb_test.py
                email: kennicetee@gmail.com
                executable: /home/kennicetee/miniconda3/envs/vision-zoo/bin/python
                git:
                    commit: 801fc061d6d438c291b5eade823c87e934837f9c
                    remote: git@github.com:mlberkeley/fa25-nmep-hw3.git
                host: honeydew
                os: Linux-5.4.0-211-generic-x86_64-with-glibc2.31
                program: /home/kennicetee/fa25-nmep-hw3/wandb_test.py
                python: CPython 3.10.19
                root: /home/kennicetee/fa25-nmep-hw3
                startedAt: "2025-10-20T20:46:49.564470Z"
                writerId: lqimk6v2zb22ks1x93jcbfxwvu1m1ome
        m: []
        python_version: 3.10.19
        t:
            "3":
                - 2
                - 16
            "4": 3.10.19
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
epochs:
    value: 20
lr:
    value: 0.0003
